vti_encoding:SR|utf8-nl
vti_syncwith_fronti\:80/ospymes:TR|22 Dec 1999 01:08:52 -0000
vti_author:SR|omicr3
vti_syncwith_localhost\\c\:\\inetpub\\wwwroot\\ospymes/c\:/inetpub/wwwroot/ospymes:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_localhost\\d\:\\matias\\ospymes\\weblocal/d\:/matias/ospymes/weblocal:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_omicron\:80/ospymes:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_localhost\\c\:\\jose maria\\nuevo ospymes/c\:/jose maria/nuevo ospymes:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_www.omicron.com.ar\:80/ospymes:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_localhost\\\\\\omicron1\\c\\inetpub\\wwwroot\\ospymes///omicron1/c/inetpub/wwwroot/ospymes:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_localhost\\c\:\\pruebaospymes/c\:/pruebaospymes:TR|22 Dec 1999 01:08:52 -0000
vti_timelastmodified:TR|06 Apr 2001 17:14:49 -0000
vti_syncwith_localhost\\c\:\\ospymes/c\:/ospymes:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_omicron1\:80/pruebaospymes:TR|22 Dec 1999 01:08:52 -0000
vti_modifiedby:SR|omicr3
vti_timecreated:TR|22 Mar 2000 15:45:44 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.2717
vti_syncwith_www.omicron.com.ar\:80/pruebaospymes:TR|22 Dec 1999 01:08:52 -0000
vti_syncwith_omicron1\:80/ospymes:TR|22 Mar 2000 15:45:44 -0000
vti_syncwith_omicron1\:80/ospymes2309:TR|22 Dec 1999 01:08:52 -0000
vti_nexttolasttimemodified:TR|22 Mar 2000 15:45:44 -0000
vti_syncwith_www.ospymes.com\:80/ospymes:TR|22 Mar 2000 15:45:44 -0000
